---
kind: pipeline
type: exec
name: default

steps:

- name: build
  commands:
   - sbt -Djline.terminal=jline.UnsupportedTerminal clean compile test:compile

- name: test
  commands:
   - sbt -Djline.terminal=jline.UnsupportedTerminal clean test

