
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2022-03-31 17:24:04.807 -0400 by glen on stella.local
// 
// a8-versions build/versioning info follows
// 
//        build_date : Thu Sep 30 12:56:07 CDT 2021
//        build_machine : ENNS-PC
//        build_machine_ip : 127.0.1.1
//        build_java_version : 11.0.11
//        build_user : raph
//        version_number : 1.0.0-20210930_1255_master
//        project_name : a8-versions
//        build_os : Linux
// 
//      

val appVersion = a8.sbt_a8.versionStamp(file("."))
val scalaLibVersion = "2.13.6"

scalacOptions in Global ++= Seq("-deprecation", "-unchecked", "-feature")

// for publishing to locus
resolvers in Global += "a8-repo" at Common.readRepoUrl()
publishTo in Global := Some("a8-repo-releases" at Common.readRepoUrl())

// for publishing to sonatype
// publishTo in Global := sonatypePublishToBundle.value
// credentials in Global += Credentials(Path.userHome / ".sbt" / "sonatype.credentials")

scalaVersion in Global := scalaLibVersion

organization in Global := "io.accur8"

version in Global := appVersion

versionScheme in Global := Some("strict")

serverConnectionType in Global := ConnectionType.Local


// not sure what but wasn't publishing javadoc so forced the settings here
lazy val codegen =
  Common
    .jvmProject("a8-codegen", file("."), "codegen")
    .settings(
      Compile / packageDoc / publishArtifact := true,
      packageDoc / publishArtifact := true,
      libraryDependencies ++= Seq(
        "org.typelevel" %% "cats-parse" % "0.3.4",
        "org.scalameta" %% "scalameta" % "4.7.5",
        "io.circe" %% "circe-core" % "0.14.1",
        "io.circe" %% "circe-generic" % "0.14.1",
        "io.circe" %% "circe-parser" % "0.14.1",
        "co.fs2" %% "fs2-io" % "3.0.2",
      )
    )


   
