
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2020-09-22 10:25:34.482 -0400 by flow on Flow-9.local
// 
// a8-versions build/versioning info follows
// 
//        build_java_version : 1.8.0_265
//        build_os : Linux
//        build_machine_ip : 127.0.0.1
//        build_user : dev
//        build_date : Wed Aug 26 15:29:40 EDT 2020
//        version_number : 1.0.0-20200826_1529_master
//        build_machine : basil
//        project_name : a8-versions
// 
//      

val scalaLibVersion = "2.12.12"

scalacOptions in Global ++= Seq("-deprecation", "-unchecked", "-feature")

resolvers in Global += "a8-repo" at Common.readRepoUrl()

publishTo in Global := Some("a8-repo-releases" at "s3://s3-us-east-1.amazonaws.com/a8-artifacts/releases")

s3CredentialsProvider in Global := { (bucket: String) =>
  import com.amazonaws.auth.{AWSStaticCredentialsProvider, BasicAWSCredentials}
  new AWSStaticCredentialsProvider(new BasicAWSCredentials(Common.readRepoProperty("publish_aws_access_key"), Common.readRepoProperty("publish_aws_secret_key")))
}

scalaVersion in Global := "2.12.12"

organization in Global := "a8"

version in Global := a8.sbt_a8.versionStamp(file("."))

serverConnectionType in Global := ConnectionType.Local



lazy val codegen =
  Common
    .jvmProject("a8-codegen", file("."), "codegen")
    .settings(
      libraryDependencies ++= Seq(
        "com.lihaoyi" %% "fastparse" % "0.4.4",
      )
    )


   
