
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2020-02-27 14:46:11.938 -0500 by glen on ROAR
// 
// a8-versions build/versioning info follows
// 
//        build_java_version : 1.8.0_222
//        build_os : Linux
//        build_machine_ip : 172.31.25.1
//        build_user : raph
//        build_date : Fri Oct 18 18:32:11 EDT 2019
//        version_number : 1.0.0-20191018_1832_master
//        build_machine : basil
//        project_name : a8-versions
// 
//      




scalacOptions in Global ++= Seq("-deprecation", "-unchecked", "-feature")

resolvers in Global += "a8-repo" at "https://accur8.jfrog.io/accur8/all/"

publishTo in Global := Some("a8-repo-publish" at "https://accur8.jfrog.io/accur8/libs-releases-local/")

credentials in Global += Credentials(Path.userHome / ".sbt" / "credentials")

scalaVersion in Global := "2.12.5"

organization in Global := "a8"

version in Global := a8.sbt_a8.versionStamp(file("."))

serverConnectionType in Global := ConnectionType.Local



lazy val codegen =
  Common
    .jvmProject("a8-codegen", file("."), "codegen")
    .settings(
      libraryDependencies ++= Seq(
        "com.lihaoyi" %% "fastparse" % "0.4.4",
      )
    )


   
